// Auto-generated by build_students_mosaic.py — do not edit manually.
// Tile positions are normalised (0–1) relative to the canvas.
export type MosaicTile = {
  name: string;
  slug: string;
  hasProfile: boolean;
  x: number;
  y: number;
  w: number;
  h: number;
};

export const CANVAS_W = 2800;
export const CANVAS_H = 1800;

export const mosaicTiles: MosaicTile[] = [
  {
    "name": "Niyati",
    "slug": "niyati",
    "hasProfile": false,
    "x": 0.0214,
    "y": 0.0333,
    "w": 0.0964,
    "h": 0.1733
  },
  {
    "name": "Muskan",
    "slug": "muskan",
    "hasProfile": false,
    "x": 0.1457,
    "y": 0.0333,
    "w": 0.1014,
    "h": 0.18
  },
  {
    "name": "Pranav",
    "slug": "pranav",
    "hasProfile": false,
    "x": 0.27,
    "y": 0.0333,
    "w": 0.0979,
    "h": 0.1756
  },
  {
    "name": "Kartik",
    "slug": "kartik",
    "hasProfile": false,
    "x": 0.3943,
    "y": 0.0333,
    "w": 0.0986,
    "h": 0.1756
  },
  {
    "name": "Prisha",
    "slug": "prisha",
    "hasProfile": false,
    "x": 0.5186,
    "y": 0.0333,
    "w": 0.0979,
    "h": 0.1756
  },
  {
    "name": "Aarna",
    "slug": "aarna",
    "hasProfile": true,
    "x": 0.6429,
    "y": 0.0333,
    "w": 0.0971,
    "h": 0.1744
  },
  {
    "name": "Shreya",
    "slug": "shreya",
    "hasProfile": false,
    "x": 0.7671,
    "y": 0.0333,
    "w": 0.1007,
    "h": 0.1778
  },
  {
    "name": "Sanchi",
    "slug": "sanchi",
    "hasProfile": false,
    "x": 0.8914,
    "y": 0.0333,
    "w": 0.1007,
    "h": 0.1789
  },
  {
    "name": "Keshav",
    "slug": "keshav",
    "hasProfile": false,
    "x": 0.0214,
    "y": 0.8078,
    "w": 0.0957,
    "h": 0.1722
  },
  {
    "name": "Anmol",
    "slug": "anmol",
    "hasProfile": false,
    "x": 0.1457,
    "y": 0.8078,
    "w": 0.1014,
    "h": 0.18
  },
  {
    "name": "Megha",
    "slug": "megha",
    "hasProfile": false,
    "x": 0.27,
    "y": 0.8078,
    "w": 0.0986,
    "h": 0.1767
  },
  {
    "name": "Snigdha",
    "slug": "snigdha",
    "hasProfile": false,
    "x": 0.3943,
    "y": 0.8078,
    "w": 0.095,
    "h": 0.1711
  },
  {
    "name": "Veenu",
    "slug": "veenu",
    "hasProfile": false,
    "x": 0.5186,
    "y": 0.8078,
    "w": 0.1014,
    "h": 0.18
  },
  {
    "name": "Raj Kumar Gayen",
    "slug": "raj-kumar-gayen",
    "hasProfile": false,
    "x": 0.6429,
    "y": 0.8078,
    "w": 0.0993,
    "h": 0.1767
  },
  {
    "name": "Harsh",
    "slug": "harsh",
    "hasProfile": false,
    "x": 0.7671,
    "y": 0.8078,
    "w": 0.0971,
    "h": 0.1733
  }
];
